function myhdlsetup(model)
% HDLSETUP(MODEL) Set Simulink model parameters for HDL code generation.
%
%   hdlsetup('model') changes the parameters of the Simulink model specified by
%   the 'model' argument to values that are commonly used for HDL code
%   generation. The specified model should be open in Simulink before you invoke
%   the hdlsetup command. The hdlsetup command uses the Simulink set_param
%   function to set up models for HDL code generation quickly and
%   consistently. The model parameters settings provided by hdlsetup are
%   intended as useful defaults, but they may not be appropriate for all your
%   applications.
%
%   See also CHECKHDL, MAKEHDL, MAKEHDLTB.

%   Copyright 2005-2011 The MathWorks, Inc.
%     

if nargin < 1
    error(message('hdlcommon:hdlcommon:hdldeprecation'));
end

if ~ischar(model)
    warning(message('hdlcommon:hdlcommon:hdlsetup'));
    return
end

% Model Parameters
set_param(model, ...
    'SingleTaskRateTransMsg','error', ...
    'MultiTaskRateTransMsg', 'error', ...
    'SolverMode',            'SingleTasking', ...
    'FixedStep',             'auto', ...
    'SaveTime',              'off', ...
    'SaveOutput',            'off', ...
    'AlgebraicLoopMsg',      'error', ...
    'InvariantConstants',    'on',...
    'SignalLogging',         'off',...
    'SampleTimeColors',      'on',...
    'ShowLineDimensions',    'on',...
    'ShowLineWidths',        'on',...
    'ShowPortDataTypes',     'on',...
    'BlockReductionOpt',     'off',...
    'ConditionallyExecuteInputs','off',...
    'InlineParams',          'on',...
    'ProdHWDeviceType',      'ASIC/FPGA->ASIC/FPGA',...
	'InheritedTsInSrcMsg',		'none');
hdlset_param(gcs, ...
	'MaskParameterAsGeneric','on',...
	'MinimizeIntermediateSignals','on')
%     'Solver',                'fixedstepdiscrete', ...

% Attach HDL Coder specific settings and implementation bindings to this
% model
attachhdlcconfig(model);

% [EOF]
