%% Parameter File
% Fs = 100000;  % Sampling Frequency
Fs = 100;  % Sampling Frequency MHz
NTaps = 128;	% Order must be even number

Ts2 = 1/Fs;		% Data Input Sampling time
Ts1 = Ts2/NTaps; % Multiplier Sampling time

Fpass = 20;   % Passband Frequency
Fstop = 24;  % Stopband Frequency
Wpass = 1;      % Passband Weight
Wstop = 1;      % Stopband Weight

% Calculate the coefficients using the FIRLS function.
Numerator  = firls(NTaps-1, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
% 周波数特性はナイキスト周波数で正規化

SimEnd=0.0025;

%% Filter Realization
Hd=dfilt.dffir(Numerator);
set(Hd, 'Arithmetic', 'fixed', ...
    'CoeffWordLength', 16, ...
    'CoeffAutoScale', false, ...
    'NumFracLength', 15, ...
    'Signed',         true, ...
    'InputWordLength', 10, ...
    'inputFracLength', 9, ...
    'FilterInternals',  'SpecifyPrecision', ...
    'OutputWordLength',  30, ...
    'OutputFracLength',  24, ...
    'ProductWordLength', 26, ...
    'ProductFracLength', 24, ...
    'AccumWordLength',   30, ...
    'AccumFracLength',   24, ...
    'RoundMode',         'floor', ...
    'OverflowMode',      'Wrap');

% block(Hd)

