function sample = fimath_sample
sample = fimath('RoundMode', 'Nearest', ...
    'OverflowMode', 'Saturate', ...
    'ProductMode', 'SpecifyPrecision', ...
    'ProductWordLength', 32, ...
    'ProductFractionLength', 30, ...
    'SumMode', 'SpecifyPrecision', ...
    'SumWordLength', 32, ...
    'SumFractionLength', 30, ...
    'CastBeforeSum', true)